### ISSUE TITLE
can u make a siIvagunner rip generator?

### ISSUE THREAD

**Issue by RealYamTalOren** [SiIvaGunner-Database/Rip-Template-Generator#3]

**Comment by AAAAAAidan** [comment]
Hello. Sorry, but I'm not sure what you're asking for. This repository is just a small HTML application for automating the creation of rip templates for the SiIvaGunner wiki. Is this what you're asking about?

**Comment by RealYamTalOren** [comment]
no i am asking about a siIvagunner rip generator

**Comment by AAAAAAidan** [comment]
Can you please elaborate on what a SiIvaGunner rip generator is supposed to be? Are you asking for something that creates actual audio for high quality rips?

**Comment by RealYamTalOren** [comment]
yes a thing that creates actual audio for high quality rips

**Comment by AAAAAAidan** [comment]
So you want to download the audio from videos on YouTube? There are already services for this type of thing. I'm sorry, but I don't have any plans to implement this in my project.

**Comment by RealYamTalOren** [comment]
where can u provide me with a download link?

**Comment by AAAAAAidan** [comment]
It depends on what you're looking for. Searching for YouTube video downloaders will bring up a lot of results you can try. I've used one call "4K Video Downloader" that has worked pretty well.

**Comment by RealYamTalOren** [comment]
i said a siIvagunner rip generator that is a video downloader

**Comment by AAAAAAidan** [comment]
I'm sorry, but I don't think this project has what you're looking for.

**Comment by RealYamTalOren** [comment]
can u make a siIvagunner rip generator?
